name: Python CI with Dependency Caching

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Cache pip dependencies
      - name: Cache pip
        id: prime-cache-d80e054
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-d80e054
          restore-keys: |
            cache-d80e054

      # Show if cache hit
      - name: Show cache result
        run: echo "Cache hit? ${{ steps.prime-cache-d80e054.outputs.cache-hit }}"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (example)
      - name: Run tests
        run: |
          echo "No tests yet"
